regions: # regions to scan
- ap-south-1 # Mumbai
- us-east-1 # N. Virginia
- global

account-blocklist: # dont touch
- "999999999999" # production

resource-types: 
  excludes: # don't delete these
  - EC2KeyPair
  - BillingCostandUsageReport
  - Budget
  - EC2DefaultSecurityGroupRule

accounts:
  "your-account-id": # AWS ACCOUNT-ID
